name: Build C# WinForms app

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v3

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build
        run: msbuild /t:Build /p:Configuration=Release

      - name: Publish
        run: msbuild /t:Publish /p:Configuration=Release /p:PublishDir="bin\Release"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: Release
          path: "*/bin/Release/"
